## LANGUAGE
defaultContentLanguage: en

## ADVANCED
build:
    buildStats:
    enable: true
    disableClasses: false
    disableIDs: true
    disableTags: false
enableRobotsTXT: true
imaging:
  quality: 75
markup:
  tableOfContents:
    ordered: true
pagination:
  pagerSize: 9
removePathAccents: true
timeout: 100000